[package]
name = "arci"
version = "0.0.4"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Abstruct Robot Control Interface"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/arci"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
auto_impl = "0.4"
futures = "0.3"
nalgebra = "0.25"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
assert_approx_eq = "1.1"
tokio-test = "0.4"
