[package]
name = "arci-gamepad-gilrs"
version = "0.0.5"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Gamepad implementation using gilrs"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/arci-gamepad-gilrs"

[dependencies]
arci = "0.0.5"
flume = "0.10"
gilrs = { version = "0.8.1", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5"
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
assert_approx_eq = "1.1"
