[package]
name = "openrr-teleop"
version = "0.0.6"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2021"
license = "Apache-2.0"
description = "openrr teleoperation library"
keywords = ["robotics", "robot"]
categories = ["algorithms", "science::robotics"]
repository = "https://github.com/openrr/openrr"

[features]
default = ["assimp"]
assimp = ["openrr-client/assimp"]

[dependencies]
arci = "0.0.6"
async-trait = "0.1"
auto_impl = "0.5.0"
k = "0.26"
openrr-client = { version = "0.0.6", default-features = false }
openrr-command = { version = "0.0.6", default-features = false }
schemars = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
assert_approx_eq = "1.1.0"
tokio = { version = "1.0", features = ["full"] }
