[package]
name = "arci-speak-cmd"
version = "0.0.5"
authors = ["Taiki Endo <taiki@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation using local command"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/arci-speak-cmd"

[dependencies]
arci = "0.0.5"
thiserror = "1.0"
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
