[package]
name = "arci-speak-audio"
version = "0.0.6"
authors = ["Koki Shinjo <sktometometo@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "arci::Speaker implementation for playing audio files"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.6"
rodio = "0.14.0"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
tokio = { version = "1", features = ["sync"] }

[target.'cfg(target_os = "linux")'.dependencies]
# https://github.com/diwic/alsa-rs/issues/81
alsa = "=0.6.0"

[dev-dependencies]
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"
