[package]
name = "openrr-command"
version = "0.0.6"
edition = "2021"
license = "Apache-2.0"
description = "openrr command line tool library"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[features]
default = ["assimp"]
assimp = ["openrr-client/assimp"]

[dependencies]
arci = { path = "../arci", version = "0.0.6" }
async-recursion = "1.0"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
k = "0.29"
openrr-client = { path = "../openrr-client", version = "0.0.6", default-features = false }
rustyline = "10.0.0"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
